#!/bin/bash
# Build Lessons Learned Index (POSIX-compatible)
# Generates docs/LESSONS-LEARNED.md from all RCA reports
# Usage: build-lessons-index.sh

set -euo pipefail

RCA_DIR="docs/rca"
OUTPUT_FILE="docs/LESSONS-LEARNED.md"
DATE=$(date +%Y-%m-%d)

# Find all RCA files with lessons
find_rca_files() {
    find "$RCA_DIR" -name "*.md" ! -name "INDEX.md" ! -name "TEMPLATE.md" ! -name "LESSONS*" -type f 2>/dev/null | sort -r
}

# Extract frontmatter field
extract_field() {
    local file="$1"
    local field="$2"
    grep "^$field:" "$file" 2>/dev/null | head -1 | sed "s/^$field: *//" | tr -d '"\r' || echo ""
}

# Collect lessons into temp files
TMP_SEVERITY="/tmp/claude/lessons_severity.txt"
TMP_CATEGORY="/tmp/claude/lessons_category.txt"
TMP_TAGS="/tmp/claude/lessons_tags.txt"
TMP_ALL="/tmp/claude/lessons_all.txt"

mkdir -p /tmp/claude
: > "$TMP_SEVERITY"
: > "$TMP_CATEGORY"
: > "$TMP_TAGS"
: > "$TMP_ALL"

total=0
while IFS= read -r file; do
    if ! grep -q "^## Уроки" "$file" 2>/dev/null; then
        continue
    fi

    title=$(extract_field "$file" "title")
    severity=$(extract_field "$file" "severity" | tr '[:lower:]' '[:upper:]')
    category=$(extract_field "$file" "category")
    tags=$(extract_field "$file" "tags")
    basename=$(basename "$file" .md)

    # Defaults
    [[ -z "$severity" ]] && severity="P3"
    [[ -z "$category" ]] && category="generic"
    [[ -z "$title" ]] && title="$basename"

    # Store for indexing
    echo "$severity|$category|$tags|$title|$file" >> "$TMP_ALL"
    echo "$severity|$title|$file" >> "$TMP_SEVERITY"
    echo "$category|$title|$file" >> "$TMP_CATEGORY"

    # Extract tags
    if [[ -n "$tags" ]]; then
        tags_clean=$(echo "$tags" | tr -d '[]\r')
        IFS=',' read -ra tag_items <<< "$tags_clean"
        for raw_tag in "${tag_items[@]}"; do
            tag=$(echo "$raw_tag" | sed 's/^ *//;s/ *$//')
            [[ -n "$tag" ]] && echo "$tag" >> "$TMP_TAGS"
        done
    fi

    total=$((total + 1))
done < <(find_rca_files)

# Build output
cat > "$OUTPUT_FILE" << 'HEADER'
# Lessons Learned (Auto-generated)

**Generated**: DATE_PLACEHOLDER
**Total Lessons**: TOTAL_PLACEHOLDER

---

## Quick Reference Card

HEADER

sed "s/DATE_PLACEHOLDER/$DATE/; s/TOTAL_PLACEHOLDER/$total/" "$OUTPUT_FILE" > /tmp/claude/header_tmp
mv /tmp/claude/header_tmp "$OUTPUT_FILE"

# By Severity
cat >> "$OUTPUT_FILE" << 'SECTION'

### By Severity

SECTION

for sev in P0 P1 P2 P3 P4; do
    count=$(awk -F'|' -v sev="$sev" '$1==sev {count++} END {print count+0}' "$TMP_SEVERITY")
    if [[ $count -gt 0 ]]; then
        echo "" >> "$OUTPUT_FILE"
        echo "#### $sev ($count lessons)" >> "$OUTPUT_FILE"
        awk -F'|' -v sev="$sev" '$1==sev {print $0}' "$TMP_SEVERITY" | while IFS= read -r line; do
            title=$(echo "$line" | cut -d'|' -f2)
            file=$(echo "$line" | cut -d'|' -f3)
            echo "- [$title](../$file)" >> "$OUTPUT_FILE"
        done
    fi
done

# By Category
cat >> "$OUTPUT_FILE" << 'SECTION'


### By Category

SECTION

cut -d'|' -f1 "$TMP_CATEGORY" | tr -d '\r' | sort -u | while IFS= read -r category_name; do
    [[ -z "$category_name" ]] && continue
    count=$(awk -F'|' -v cat="$category_name" '$1==cat {count++} END {print count+0}' "$TMP_CATEGORY")
    if [[ $count -gt 0 ]]; then
        echo "" >> "$OUTPUT_FILE"
        echo "#### $category_name ($count lessons)" >> "$OUTPUT_FILE"
        awk -F'|' -v cat="$category_name" '$1==cat {print $0}' "$TMP_CATEGORY" | while IFS= read -r l; do
            title=$(echo "$l" | cut -d'|' -f2)
            file=$(echo "$l" | cut -d'|' -f3)
            echo "- [$title](../$file)" >> "$OUTPUT_FILE"
        done
    fi
done

# By Tag
cat >> "$OUTPUT_FILE" << 'SECTION'


### Popular Tags

SECTION

sort "$TMP_TAGS" | tr -d '\r' | uniq -c | sort -rn | head -10 | while read -r count tag; do
    echo "- \`$tag\` ($count lessons)" >> "$OUTPUT_FILE"
done

# Statistics
critical=$(grep -E '^(P0|P1)\|' "$TMP_SEVERITY" | wc -l | tr -d ' ')
categories=$(cut -d'|' -f1 "$TMP_CATEGORY" | tr -d '\r' | sort -u | wc -l | tr -d ' ')
tags_count=$(sort "$TMP_TAGS" | tr -d '\r' | uniq | wc -l | tr -d ' ')

cat >> "$OUTPUT_FILE" << STATISTICS


---

## Statistics

| Metric | Value |
|--------|-------|
| Total Lessons | $total |
| Critical (P0/P1) | $critical |
| Categories | $categories |
| Unique Tags | $tags_count |

---

## How to Search

\`\`\`bash
# Find lessons by severity
./scripts/query-lessons.sh --severity P1

# Find lessons by tag
./scripts/query-lessons.sh --tag docker

# Find lessons by category
./scripts/query-lessons.sh --category deployment

# Show all lessons
./scripts/query-lessons.sh --all
\`\`\`

---

*This file is auto-generated by scripts/build-lessons-index.sh*
*Do not edit manually - changes will be overwritten*
STATISTICS

# Cleanup
rm -f "$TMP_SEVERITY" "$TMP_CATEGORY" "$TMP_TAGS" "$TMP_ALL"

echo "✓ Generated $OUTPUT_FILE"
echo "  Total lessons: $total"
echo "  Categories: $categories"
echo "  Tags: $tags_count"
