#!/bin/bash
# Render the tracked Moltis runtime env file from CI-provided secrets.

set -euo pipefail

OUTPUT_PATH=""
MOLTIS_DOMAIN_VALUE="${MOLTIS_DOMAIN:-moltis.ainetic.tech}"
MOLTIS_RUNTIME_CONFIG_DIR_VALUE="${MOLTIS_RUNTIME_CONFIG_DIR:-/opt/moltinger-state/config-runtime}"

usage() {
    cat <<'EOF'
Usage: render-moltis-env.sh --output <path> [--domain <domain>] [--runtime-config-dir <path>]

Renders the Moltis .env payload from environment variables provided by CI.
EOF
}

assert_single_line() {
    local key="$1"
    local value="$2"

    case "$value" in
        *$'\n'*|*$'\r'*)
            echo "render-moltis-env.sh: $key must be single-line so it can be rendered into .env" >&2
            exit 2
            ;;
    esac
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_PATH="${2:-}"
            shift 2
            ;;
        --domain)
            MOLTIS_DOMAIN_VALUE="${2:-}"
            shift 2
            ;;
        --runtime-config-dir)
            MOLTIS_RUNTIME_CONFIG_DIR_VALUE="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "render-moltis-env.sh: unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -z "$OUTPUT_PATH" ]]; then
    echo "render-moltis-env.sh: --output is required" >&2
    usage >&2
    exit 2
fi

assert_single_line "MOLTIS_PASSWORD" "${MOLTIS_PASSWORD:-}"
assert_single_line "OLLAMA_API_KEY" "${OLLAMA_API_KEY:-}"
assert_single_line "TAVILY_API_KEY" "${TAVILY_API_KEY:-}"
assert_single_line "TELEGRAM_BOT_TOKEN" "${TELEGRAM_BOT_TOKEN:-}"
assert_single_line "TELEGRAM_ALLOWED_USERS" "${TELEGRAM_ALLOWED_USERS:-}"
assert_single_line "TELEGRAM_WEBHOOK_URL" "${TELEGRAM_WEBHOOK_URL:-}"
assert_single_line "TELEGRAM_WEBHOOK_SECRET" "${TELEGRAM_WEBHOOK_SECRET:-}"
assert_single_line "MOLTIS_DOMAIN" "$MOLTIS_DOMAIN_VALUE"
assert_single_line "MOLTIS_RUNTIME_CONFIG_DIR" "$MOLTIS_RUNTIME_CONFIG_DIR_VALUE"

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" <<EOF
# Auto-generated by CI/CD from GitHub Secrets
# DO NOT EDIT MANUALLY - changes will be overwritten

# Authentication
MOLTIS_PASSWORD=${MOLTIS_PASSWORD:-}

# LLM Primary - OpenAI Codex OAuth runtime state lives under
# MOLTIS_RUNTIME_CONFIG_DIR; no static API key is rendered here.

# LLM Fallback - Ollama Cloud (optional, for cloud models)
OLLAMA_API_KEY=${OLLAMA_API_KEY:-}

# Web Search - Tavily
TAVILY_API_KEY=${TAVILY_API_KEY:-}

# Telegram Bot
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL:-}
TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET:-}

# Domain
MOLTIS_DOMAIN=${MOLTIS_DOMAIN_VALUE}
MOLTIS_RUNTIME_CONFIG_DIR=${MOLTIS_RUNTIME_CONFIG_DIR_VALUE}
EOF
