#!/usr/bin/env bash
# Mirror tracked project knowledge into Moltis' officially indexed memory path.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

KNOWLEDGE_ROOT="${PROJECT_ROOT}/knowledge"
RUNTIME_HOME=""
OUTPUT_RELATIVE_PATH="memory/project-knowledge.md"
SERVICE_UID="${MOLTIS_SERVICE_UID:-1000}"
SERVICE_GID="${MOLTIS_SERVICE_GID:-1000}"

usage() {
    cat <<'EOF'
Usage:
  sync-moltis-project-knowledge.sh \
    --runtime-home <path> \
    [--knowledge-root <path>] \
    [--output-relative-path <path>]

Copies tracked markdown knowledge into the canonical Moltis runtime memory path
so the built-in memory backend can index it without relying on optional
watch_dirs behavior.
EOF
}

log() {
    echo "[sync-moltis-project-knowledge] $*" >&2
}

require_argument() {
    local name="$1"
    local value="$2"

    if [[ -z "$value" ]]; then
        echo "sync-moltis-project-knowledge.sh: missing required argument: $name" >&2
        usage >&2
        exit 64
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --knowledge-root)
            KNOWLEDGE_ROOT="${2:-}"
            shift 2
            ;;
        --runtime-home)
            RUNTIME_HOME="${2:-}"
            shift 2
            ;;
        --output-relative-path)
            OUTPUT_RELATIVE_PATH="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "sync-moltis-project-knowledge.sh: unknown argument: $1" >&2
            usage >&2
            exit 64
            ;;
    esac
done

require_argument "--runtime-home" "$RUNTIME_HOME"

if [[ ! -d "$KNOWLEDGE_ROOT" ]]; then
    echo "Knowledge root not found: $KNOWLEDGE_ROOT" >&2
    exit 1
fi

if [[ ! -d "$RUNTIME_HOME" ]]; then
    echo "Runtime home not found: $RUNTIME_HOME" >&2
    exit 1
fi

mapfile -t KNOWLEDGE_FILES < <(
    find "$KNOWLEDGE_ROOT" -type f -name '*.md' ! -name 'AGENTS.md' | sort
)

if [[ "${#KNOWLEDGE_FILES[@]}" -eq 0 ]]; then
    echo "No markdown knowledge files found under: $KNOWLEDGE_ROOT" >&2
    exit 1
fi

OUTPUT_PATH="$RUNTIME_HOME/$OUTPUT_RELATIVE_PATH"
mkdir -p "$(dirname "$OUTPUT_PATH")"
tmp_output="$(mktemp "$RUNTIME_HOME/.knowledge-sync.XXXXXX")"

{
    cat <<'EOF'
# Project Knowledge Bundle

This file is generated from tracked repository knowledge so Moltis can index it
via the default `~/.moltis/memory/*.md` contract described in the official
Memory documentation.

Do not edit this file by hand. Update the tracked `knowledge/` sources instead.
EOF

    for knowledge_file in "${KNOWLEDGE_FILES[@]}"; do
        rel_path="${knowledge_file#$KNOWLEDGE_ROOT/}"
        rel_path="knowledge/${rel_path}"
        printf '\n\n---\n\n'
        printf '## Source: %s\n\n' "$rel_path"
        cat "$knowledge_file"
        printf '\n'
    done
} >"$tmp_output"

mv "$tmp_output" "$OUTPUT_PATH"

if [[ "$(id -u)" -eq 0 ]]; then
    chown "$SERVICE_UID:$SERVICE_GID" "$OUTPUT_PATH"
fi
chmod 640 "$OUTPUT_PATH" 2>/dev/null || true

log "synced ${#KNOWLEDGE_FILES[@]} knowledge files into $OUTPUT_PATH"
